- packages/usdk/cli.js
- packages/usdk/lib/version.mjs
- Add version check to the usdk, execute before running any command. Not running process.exit() if there is a version mismatch.
> Add version check

- packages/usdk/lib/create.mjs
- packages/usdk/lib/git-util.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/agent-json-util.mjs
Check git version instead of npm version.
> fix: Check git version

- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
> wrap player inside "data"

- packages/usdk/cli.js
- packages/usdk/lib/authenticate.mjs
- packages/usdk/lib/commands.mjs
- packages/usdk/lib/create.mjs
- packages/usdk/util/agent-auth-util.mjs
- packages/usdk/util/dotenv-util.mjs
Fixes https://github.com/UpstreetAI/monorepo/issues/587
> `usdk authenticate` command

- apps/chat/app/new/editor.tsx
- apps/docs/content/docs/api/integrations.mdx
- package-lock.json
- packages/usdk/packages/upstreet-agent/packages/react-agents/default-components.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/agent-features.mjs
Rename the component for cleaner usage.
> DiscordBot -> Discord component

- apps/docs/content/docs/api/integrations.mdx
add a new line about creating agent
> add a new line in discord integration instructions

- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
This PR incudes fix for the following issue:
- Emit join event when local player joins the room.
> Fix for Player is required exception on FE

- packages/usdk/cli.js
> Unlock custom voice command

- packages/usdk/LICENSE
- packages/usdk/package.json
GPL is better for our usecase than ISC.
> chore: add GPL license

- README.md
- apps/docs/content/docs/meta.json
Preliminary README for monorepo (pre name-change, pre-contributors)
> docs: New README for monorepo, phase 1

- apps/docs/content/docs/examples/stateful-agent.mdx
1) Import the relevant libraries that are being used in the code.
2) Import the guessing game component into the agent.
> stateful-agent docs updated

- packages/usdk/packages/upstreet-agent/packages/react-agents/util/audio-perception.mjs
- packages/usdk/util/connect-utils.mjs
Small logging cleanups in the vad implementation.
> Vad cleanup

- packages/usdk/lib/create.mjs
- packages/usdk/package.json
- packages/usdk/packages/upstreet-agent/package.json
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/devices/video-input.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/agent-features.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/generate-video.mjs
- packages/usdk/util/connect-utils.mjs
This PR merges all the individual fixes which occurred for the Discord component:
- fix for formatDiscordBotChannels to accept and process an array rather then a string
- fix for outdated DiscordBot tag being used inside the agent-features.mjs file
- fix for Jimp.fromBuffer function not defined error (updated package version and package import)
- fix for using updated image.resize params for Jimp image resize zod schema
- appends the attachments containing url's to the Discord bots text response
> Discord component updates

- packages/usdk/packages/upstreet-agent/packages/codecs/audio-client.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/devices/audio-transcriber.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/lib/discord/discord-client.js
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/audio-merger.mjs
- Add AudioMerger
- Merge discord audio streams per user
- Pass merged stream to VAD transcriber
> Merge audio streams in discord client

- packages/usdk/packages/upstreet-agent/packages/react-agents/util/audio-perception.mjs
This PR adds sending customisable VAD options to the VAD server
> Add customisable vadOptions support for VAD component

- packages/usdk/lib/deploy.mjs
Hit agents with initial request to bootstrap the durable object.
> Bootstrap deployed agents by hitting them

- apps/chat/components/chat/chat.tsx
- apps/chat/components/chat/embed-chat.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/entry.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/worker.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-wrangler/wrangler-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/agent-renderer.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/app-context-value.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/entry.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/hooks.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/runtime.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
Log prompts when `-g` is passed.
> Debug flag for prompt output

- apps/chat/app/globals.css
- apps/chat/components/chat/chat-list.tsx
- apps/chat/components/chat/chat-panel.tsx
- apps/chat/components/chat/chat.tsx
- apps/chat/components/chat/desktop-chat.tsx
- apps/chat/components/chat/embed-chat.tsx
- apps/chat/components/prompt-form.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- electron ui updates
- added minimize maximize window for the desktop chat
- applied UI styles from figma to chat window
- code and style cleanup
> Electron UI Updates

- packages/usdk/lib/create.mjs
catch and display not logged in error without stack trace
> Abstract not logged in stack trace on usdk create when logged out

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/default-components.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/evaluators/basic-evaluator.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/evaluators/react-evaluator.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/hooks.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/loops/chat-loop.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/loops/infinite-loop.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/runtime.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
- pnpm-lock.yaml
Add pluggable cognitive loops infrastructure.
> Cognitive loops support

- packages/usdk/cli.js
- packages/usdk/lib/chat.mjs
- packages/usdk/lib/run-agent.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/entry.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/worker.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-wrangler/wrangler-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/agent-renderer.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/app-context-value.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/entry.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/evaluators/basic-evaluator.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/evaluators/react-evaluator.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/runtime.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/debug-levels.mjs
- packages/usdk/util/connect-utils.mjs
Adds number support to `-g`, for scoping the agent's logging.
> Log levels support

- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/worker.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/loops/chat-loop.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/loops/infinite-loop.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/debug-levels.mjs
Fixes debug options parsing and flag checking, especially for the React runtime.
> Fix debug logging

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
PR adds a Discord Status request error check to throw exception in failure cases.
(currently proceeds on error hence required on high prio)
> Add Discord client Status error check

- packages/usdk/packages/upstreet-agent/packages/react-agents/components/base-components.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/components/default-components.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/index.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/loops/chat-loop.tsx
Part 1 of breaking out all components to separate files for docsgen.
> Move components to components/

- apps/chat/app/desktop/[id]/page.tsx
- apps/chat/app/desktop/layout.tsx
- apps/chat/app/layout.tsx
- apps/chat/components/body.tsx
- apps/chat/components/loading.tsx
- apps/chat/components/main-wrap.tsx
- apps/chat/components/providers.tsx
- apps/chat/contexts/GlobalContext.ts
- apps/chat/lib/client/hooks/use-loading.tsx
- apps/chat/lib/types.ts
- fixed all the loading issues, jank screen on load and twitching 
- updated global context and cleaned up the code
- mode now available in global context ( Desktop, Web, Embed ) for usage
> UI updates

- packages/usdk/packages/upstreet-agent/packages/react-agents/components/plugins/auto-task.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/index.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
- pnpm-lock.yaml
Add a component for starting/managing tasks
> Auto task support

- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
This should be quicker and more secure.
> Directly inject token to electron

- apps/docs/content/docs/api/integrations/x.mdx
Add in explicit and detailed action steps for setting up the Twitter component on both X Developer portal and the <Twitter token=".."> component
> Update Twitter Component Docs

- packages/usdk/packages/upstreet-agent/packages/react-agents/util/fetch.mjs
Return parsed response for the chat completion call
> return parsed string as response in fetchJsonCompletion

- apps/chat/components/chat/chat-panel.tsx
- apps/chat/components/chat/chat.tsx
- apps/chat/components/chat/desktop-chat.tsx
- apps/chat/components/prompt-form.tsx
- apps/chat/lib/hooks/use-scroll-anchor.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/preload.mjs
-  poke doesn't work ( DONE )
- pfp default still shows nothing ( DONE )
- impossible to see the typing indicator ( DONE )
- still unfinished media picker ( DONE )
- close button throws error ( DONE )
> Desktop fixes

- packages/usdk/lib/deploy.mjs
- Update the Deployer response processing
- Remove deprecated format for reading agentJson for data.vars to use the deployer result as is
> Update Deploy Response Processing

- packages/usdk/lib/deploy.mjs
Catch 'error' event form the log stream, console log error
> catch and throw error event on deploy

- packages/usdk/lib/create.mjs
- Add node_modules path for filter windows
> filter out node modules on windows

- packages/usdk/package.json
- packages/usdk/packages/upstreet-agent/packages/react-agents-browser/package.json
- packages/usdk/packages/upstreet-agent/packages/react-agents-client/package.json
add missing react-agents package, add zod-to-json-schema to usdk package json, fix upstreet-agent path in react-agent-browser
> Fix path and add missing packages

- packages/usdk/packages/upstreet-agent/packages/react-agents/components/plugins/rag-memory.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/components/util/message-utils.tsx
**Problem:**
No memories are loaded until the user sends their first message after an agent boots up
**Solution**:
Load conversation memories when the Rag component is mounted
> Load initial RAG memories on component mount

- packages/usdk/packages/upstreet-agent/durable-object.tsx
- packages/usdk/packages/upstreet-agent/main.jsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/chats-specification.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/entry.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/react-agents.d.ts
It was using the userId from the JWT instead of the agentId from the agent.json.
> Fix chat specifications user_id keying

- packages/usdk/lib/create.mjs
create agent in the current command directory, use agent name as directory name
- Replace spaces in agent name with "_" i.e AI Agent #41414 -> AI_AGENT_#41414
> Create Agent On CWD and using Agent name as Directory name

- apps/chat/app/new/editor.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-browser/browser-runtime.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents-browser/worker.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/agent-renderer.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/hooks.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/root.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/storage/pglite-storage.mjs
Makes PGliteStorage the default storage adapter in the browser runtime.
> PGliteStorage in the browser

- apps/chat/app/create/builder.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/agent-features-spec.mjs
- code cleanup
- updated agent feature specs
> Builder Updates
