UpstreetAI/upstreet-core

- .github/workflows/usdk-test.yml
- packages/usdk/cli.js
- packages/usdk/lib/commands.mjs
- packages/usdk/lib/version.mjs
Add Node.js version check and SDK version comparison
- Implemented `checkNodeVersion` function in `version.mjs` to ensure the current Node.js version meets the minimum requirement specified in `package.json`.
- Added `currentSdkVersion` and `latestSdkVersion` functions to retrieve the current and latest SDK versions.
- Integrated `checkNodeVersion` into `cli.js` to enforce Node.js version checks at runtime.
SOT for min required node check: package.json -> engines -> node
> Node version check

- apps/chat/components/ui/multiplayer-actions.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
- This PR fixes the player.getPlayerSpec() is not a function issue.
- event data set to remotePlayer only since that is being extracted and used in codebase
VirtualPlayer inside e.data does not have the getPlayerSpec() function and is defined on the Player object
> Fix player spec not found fe

- apps/chat/components/ui/multiplayer-actions.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
This PR handles the case where the agent joining the room has playerSpec data initialised.
- adds a playerSpecUpdate event to the react-agents-client and a listener for the event in the multiplayer actions
> Fix PlayerSpec missing when agent joins

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/agent-renderer.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/app-context-value.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/hooks.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
Adds useEnv hook to access the `.env.txt` contents (parsed as an object).
Not to be confused with `useEnvironment()`, which is the `'development'` vs `'production'` string. Might be a bad name.
> useEnv hook

- apps/chat/components/ui/multiplayer-actions.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
This PR improves the player addition logic by ensuring players are added to the playersMap only after their playerSpec is set.
Prevent early join events without the playerSpec initialised (causing getPlayerSpec crashes since an early join has the playerSpec undefined and needs to wait for an update event)
> Sync Player addition with PlayerSpec

- packages/usdk/lib/create.mjs
- packages/usdk/lib/directory-util.mjs
This PR only adds additional logs to the agent creation process for more frequent state update logs improving DX and to let users know accurately of the current creation steps being completed.
Previously users reported not being aware of where the installation process was when provided additional flags such as the prompt argument (-p "...")
> Add additional logs on create process updates

- package-lock.json
The docs build started failing at the `postinstall` script, where it was unable to find `fumadocs-core`:
```
(base) saadbazaz@Saads-MacBook-Pro monorepo % npm i
npm error code 1
npm error path /Users/saadbazaz/Projects/monorepo/apps/docs
npm error command failed
npm error command sh -c fumadocs-mdx
npm error node:internal/modules/esm/resolve:839
npm error   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
npm error         ^
npm error
npm error Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fumadocs-core' imported from /Users/saadbazaz/Projects/monorepo/node_modules/fumadocs-mdx/dist/chunk-FXIX4XBC.mjs
npm error     at packageResolve (node:internal/modules/esm/resolve:839:9)
npm error     at moduleResolve (node:internal/modules/esm/resolve:908:18)
npm error …
```
> fix: docs build error

- apps/chat/next.config.js
- allows the /embed route pass the CSP, testing live
> allow all ancestor origins for testing

- apps/docs/app/llms.txt/route.ts
- apps/docs/package.json
- package-lock.json
Inspired by:
- Fumadocs: https://github.com/fuma-nama/fumadocs/blob/dev/apps/docs/app/llms-full.txt/route.ts
- FireCrawl: https://llmstxt.firecrawl.dev/
Why for docs?
Because that way other LLMs can learn about this Agentic framework and refer it :D
> feat(docs): add llms txt

- packages/usdk/packages/upstreet-agent/packages/codecs/packages/libopusjs/libopus.wasm.fs.js
- packages/usdk/packages/upstreet-agent/packages/codecs/packages/mpg123-decoder/src/MPEGDecoder.fs.js
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/entry.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/util/path-util.mjs
I needed to generate the command reference automatically from `usdk/cli.js`. But I was getting wasm import errors due to path.
So to resolve this, I have created this PR.
This PR is a more focused variant of #656 .
It only edits the `usdk`-related files, so that the team can easily review.
- Adds an edge case in `getCurrentDirname` which falls back to use `process.cwd()` if `import.meta` doesn't work.
- Updates all instances of `getCurrentDirname` to also pass `process`
> fix: add path fallback

- packages/usdk/cli.js
I needed to generate the command reference automatically from `usdk/cli.js`. But every time I import and run `main`, it also runs `usdk`. I want to retrieve just the `program` separately, so I can mess with it.
So to resolve this, I have created this PR.
This PR is a more focused variant of #656 .
It only edits the `usdk`-related files, so that the team can easily review.
- Separate `createProgram` from `main`
- Adds try-catch on each step to ensure we know if something is broken
> feat: separate program creation from invocation

- apps/docs/content/docs/(getting-started)/create-an-agent.mdx
- apps/docs/content/docs/(getting-started)/import-an-agent.mdx
- apps/docs/content/docs/(getting-started)/meta.json
Adds docs for importing agents from Tavern Character Cards: https://github.com/malfoyslastname/character-card-spec-v2
> Import agent docs

- packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs
This PR fixes the following issue:
https://github.com/orgs/UpstreetAI/projects/7/views/1?pane=issue&itemId=88644610&issue=UpstreetAI%7Cupstreet-core%7C677
- case where the join event was fired before the remotePlayer's playerSpec was set leads to player not being in the playersMap
https://github.com/UpstreetAI/upstreet-core/blob/0272276f25154a7d997e094002aacbb946f64a0b/packages/usdk/packages/upstreet-agent/packages/react-agents-client/react-agents-client.mjs#L179
hence need to add the player to the playersMap when when 'update' event with 'playerSpec' key is fired and the playersId is not in the playersMap
> Add missing playersMap player addition in playerSpec update

- packages/usdk/lib/chat.mjs
- packages/usdk/lib/run-agent.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/entry.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/worker.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-wrangler/wrangler-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/agent-renderer.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/app-context-value.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/entry.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/hooks.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/types/agents.d.ts
Pass down `init` argument to agent runtime, with hooks to access it. This allows optional initialization to be passed down on a per-agent basis, which is very useful for development.
> Init args support

- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/watcher.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-node/worker.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-wrangler/wrangler-runtime.mjs
The runtime processes weren't properly feeding sigterm down to the children, leaving dangling runtimes.
Add
```
process.addListener('SIGTERM', () => {
```
to each.
> Add missing SIGTERM listeners

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
Add guard to dm conversation creation (users having common servers, dm event for each guild)
Fixes:
https://github.com/UpstreetAI/upstreet-core/issues/689
- Discord Agent Bot goes through each member in guild and sends 'dmconnect' event to the connected user
- connected user on receiving the 'dmconnect' creates a new conversation object, uses the discord user's userId as hash and adds it to the manager
- so here since the userId is being used to create the conversation object key
- a user with common servers with the bot will be sent twice with dmconnect (from each guild/server)
- since this is dm, there must be no duplicate dm conversations for the same user
> fix(dm): Prevent creating duplicate conversations for users in multiple common servers/on reconnection

- packages/usdk/lib/zip-util.mjs
Issue:
- ENAMETOOLONG
Solution:
- Add ignore function to the recursiveReaddir function call to ignore all files with node_modules
> Add node_modules to ignore function while recursiveReaddir

- packages/usdk/packages/upstreet-agent/packages/react-agents/runtime.ts
Issue:
- Chat perception being evaluated twice, once with null conversation and once with the relevant conversation
- handle null conversation more explicitly to avoid multiple reasons in a chat conversation
> Specific conversation object argument based filtering for handling Chat Perception 

- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/electron-main.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents-electron/lib/updateIgnoreMouseEvents.js
Now the mouse properly passes through transparent elements, so that the UI can stop occluding my screen while working.
> Pass mouse events through transparent elements

- packages/usdk/lib/npm-util.mjs
Wrong Path resolution on Windows for pnpmPackageJson.
- use require.resolve to resolve path reliably
> Fix Broken pnpmPackageJson Path Resolution on Windows

- packages/usdk/packages/upstreet-agent/package.json
Fix for:
- add jest dep to upstreet-agent package.json
> add missing jest dep to upstreet-agent

- packages/usdk/packages/upstreet-agent/packages/react-agents/util/agent-json-util.mjs
Generate a random number between:
- min 10000 
- max 99999
- Add to the default name spec
> Generate and Add numeric suffix to the default AI Agent name

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/components/core/chat.tsx
- packages/usdk/packages/upstreet-agent/packages/react-agents/components/util/default-components.tsx
This PR adds an abstracted chat message user mention support for the Agent's.
Implementation:
- Adds a "mentionsRegex" to the conversation object. This will be used to define the platforms specific mentions format to the conversation.
- The "mentionsRegex" MUST use the named capture group format since that will be used to format the outgoing messages of the agent
- "mentionsRegex" is passed in via the Conversation object constructor through for the binded conversations.
- The Clients also provide the **mentionId** of the user in the Player's spec which is used during the outgoing message formatting
- Incoming messages to the agent are check for having mentions and if mentions are their the message is formatted (using "getIncomingMessageMentions" and "formatOutgoingMessageMentions")
- The …
> Abstracted Chat Message User Mentions support

- packages/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs
- packages/usdk/packages/upstreet-agent/packages/react-agents/agent-defaults.mjs
Fix for the wrangler toml name, to use the "user-agent-xxx" syntax as used previously everywhere for the agent cloud url
> Fix name field for wrangler toml

- packages/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs
- pnpm-lock.yaml
Uses a lookup process to link node modules in the pre-run agent install process. This should help resolution when the `usdk` is installed using `npm`.
> Fix install agent linkage

- .github/workflows/usdk-test.yml
- packages/usdk/package.json
- packages/usdk/packages/upstreet-agent/package.json
- packages/usdk/packages/upstreet-agent/packages/react-agents-browser/package.json
- pnpm-lock.yaml
This should fix:
```
Error: install agent link: could not find root for: browser-util-inspect
at file:///Users/xiaosong/.nvm/versions/node/v23.5.0/lib/node_modules/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs:115:15
at async Promise.all (index 6)
at async addDependencies (file:///Users/xiaosong/.nvm/versions/node/v23.5.0/lib/node_modules/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs:102:5)
at async installAgent (file:///Users/xiaosong/.nvm/versions/node/v23.5.0/lib/node_modules/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs:119:3)
at async ReactAgentsNodeRuntime.start (file:///Users/xiaosong/.nvm/versions/node/v23.5.0/lib/node_modules/usdk/packages/upstreet-agent/packages/react-agents-node/node-runtime.mjs: …
```
> Postinstall upstreet-agents from usdk

- packages/usdk/packages/upstreet-agent/package.json
- packages/usdk/packages/upstreet-agent/packages/codecs/packages/libopusjs/libopus.wasm.fs.js
- packages/usdk/packages/upstreet-agent/packages/codecs/packages/mpg123-decoder/src/MPEGDecoder.fs.js
- packages/usdk/packages/upstreet-agent/packages/path-util/package.json
- packages/usdk/packages/upstreet-agent/packages/path-util/path-util.mjs
- pnpm-lock.yaml
It was being used in multiple submodules.
> Modularize path util

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts
This PR depends on:
https://github.com/UpstreetAI/upstreet/pull/1451
Use displayName for the text message to maintain consistency with the agent playerSpec.
- Agent spec uses the "displayName" for the discord user
- Incoming messages were using the "username"
- Updated the incoming discord text messages to use the "displayName" to maintain consistency between the Agent spec for the conversation
> Use DisplayeName for Discord Text Messages

- packages/usdk/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts
- packages/usdk/packages/upstreet-agent/packages/react-agents/components/core/chat.tsx
Update the Agent to use:
- "@name" format instead of using "@userId" to completely avoid userId's being included in say messages
- update outgoing messages formatting functions to use the agent "name" provided and use their platform mentionId
> Update Mention to use User/Agent name instead of Id

- packages/usdk/packages/upstreet-agent/packages/react-agents-node/install-agent.mjs
Potentially solves issues where `usdk build` only copied react-agents related `node_modules`, but not locally installed packages in the agent's `package.json`.
Tested locally on my side:
- `usdk build`, worked
- `usdk chat`, worked.
> fix: install agent's package json on build

- packages/usdk/package.json
USDK was not properly working in the deployer, because when the dockerfile was being built, the preinstall script would silently fail, and hence the upstreet-agents dependency would be missing.
This ChatGPT chat covers the issue: https://chatgpt.com/share/67975f17-8840-800e-9e83-efa9820780ad
The fix was to update the syntax in the `preinstall` script in usdk's package.json so it could work in posix-compliant operating systems.
Needs testing on Windows.
> fix: preinstall script syntax issue
